### PR TITLE
Closes #15: Add missing protocol to BoardGameGeek images.

### LINKED ISSUE #15: Can't add board game from online sources
When I try to add a new board game from online sources, the application crashes. I am able to search, but when I click a result and choose to add it it crashes. It looks like the problem is that the image URL is missing the protocol, but I'm having trouble walking through how this url is generated.

### PR DESCRIPTION
**Pull request by jamesiarmes**
This fixes the application crash when adding a new board game from BoardGameGeek.

### CODE REVIEW

**Comment by jamesiarmes** [comment]
Any update on this? I'm going to be reorganizing some things this weekend and was hoping to be able add my board games to my collection.

**Comment by gjtorikian** [comment]
Yep yep, sorry, taking a look at it now. It's the New Year so my availability's limited but I definitely want to see this working.

**Comment by gjtorikian** [comment]
Handled by https://github.com/gjtorikian/Shelves/commit/41ec18eff7fafdb122f02405b98f7538cdcbd14e.

The images don't show up in the list view, but they do now show up in the shelf when the image is added. I know why they're not showing up in the list view but don't have time at the moment to fix it up (it'd require a second API call).

Thanks again for this though--it's now out as 3.7.0.

**Comment by JazzyA** [comment]
Hi Garen,

 

As a humble Shelves user rather than coder, is there any way I can benefit from the ongoing dev work on Shelves. I mean can I migrate to the latest alpha/beta version without coding skills?

Many thanks, Adrian

 

Adrian Ralph Samuels

SAP PLM /PPM Consultant

iTibet Limited

**Comment by jamesiarmes** [comment]
@gjtorikian Excellent, thanks for that. I've updated on my phone and the images are working for me in both shelf and list views.

**Pull request closed without merging**
